name: 自动fork

on:
  schedule:
    - cron: '* * * * */1'
jobs:
  repo-sync:
    runs-on: windows10
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: Drak-God
          head: main
          base: main
